apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen
  namespace: argocd2
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/rollouts-demo.git
    targetRevision: HEAD
    path: examples/blue-green
  destination:
    server: https://kubernetes.default.svc
    namespace: rollouts